### ISSUE TITLE
Heists System Overhaul

### ISSUE THREAD

**Issue by DevulTj** [Monolith-RP/issues#6]
**TODO: More design info**

- Completely revamped heist system
- Built in the gamemode, not as an addon
- Closely integrated with our game systems

Bags would be a new equipment slot in the inventory (not persistent) and would add an additional inventory below the current inventory to store heist items in. They won't be able to go in your main inventory.

Either this, or make heist items regular items, that can be stored in your inventory - but will be removed on disconnect and cannot go into the bank or containers.

- [ ] Bank Heist
- [x] Cargo Ship Heist
- [x] Jewellery Store Heist
- [ ] Random Property Heists (via Monolith-RP/gamemode#8)

**Comment by DevulTj** [comment]
@R4K0 @m4rkey @sildotdev we need to group up and discuss the implementation and scope of this feature
